name: getrelease
on: 
  pull_request:
  
     
   
env:
    release_version_tag : "" 
    
     
jobs: 
  getrelease:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v3      
            
      - name: Fetch latest release version
        id: release
        continue-on-error: true 
        run : |
               
               docker-compose -f docker-compose.yml up -d
               docker ps --format '{{.Image}}' >> docker_images.txt
               
      - uses: snyk/actions/setup@master
      - name: Snyk monitor
        run: 
              | 
                touch result.txt
                echo "snyk test results:" > result.txt
                readarray -t imageslist < docker_images.txt
                snyk auth ${{ secrets.SNYK_TOKEN }}
                for image_name in "${imageslist[@]}"; do
                 echo "$image_name: " >> result.txt
                 snyk container test  $image_name  --json-file-output=snyk.json || true
                 echo "print snyk:"
                 cat snyk.json
                 jq ' .summary   ' snyk.json  | sed 's|[",]||g' >> result.txt
                 jq ' .vulnerabilities[] | {id,title,severity} ' snyk.json  >> result.txt
                 done
                cat result.txt | sed 's|[{"},]||g' > final_result.txt
               
      - name: Update snyk result as pr comment
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ always() }}
        with:
         filePath: final_result.txt 