name: Snyk Scan for Python Vulnerabilities

on:
  pull_request:
    types: [opened]

jobs:
  scan:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Snyk to check vulnerabilities in Python
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          json: true
          args: --severity-threshold=high

      # - name: Extract Snyk scan status
      #   uses: sergeysova/jq-action@v2
      #   id: snyk_success
      #   with:
      #     cmd: 'if [[ "$(jq .ok snyk.json -r)" == "true" ]]; then echo ":white_check_mark:"; else echo ":x:"; fi'

      # - name: Extract Snyk scan summary
      #   uses: sergeysova/jq-action@v2
      #   id: summary
      #   with:
      #     cmd: 'jq .summary snyk.json -r'

      # - name: Extract Snyk scan vulnerability description
      #   uses: sergeysova/jq-action@v2
      #   id: description
      #   with:
      #     cmd: 'echo -e `jq .remediation.unresolved[0].description snyk.json -r`'
      #     multiline: true

      - uses: snyk/actions/setup@master
      - name: Monitor
        run: | 
          touch result.txt
          echo "snyk test results:" > result.txt
          readarray -t imageslist < docker_images.txt
          snyk auth ${{ secrets.SNYK_TOKEN }}
          for image_name in "${imageslist[@]}"; do
          echo "$image_name: " >> result.txt
          snyk container test  $image_name  --json-file-output=snyk.json || true
          echo "print snyk:"
          cat snyk.json
          jq ' .summary   ' snyk.json  | sed 's|[",]||g' >> result.txt
          jq ' .vulnerabilities[] | {id,title,severity} ' snyk.json  >> result.txt
          done
          cat result.txt | sed 's|[{"},]||g' > final_result.txt

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            SNYK scan results: \
            ${{ steps.snyk_success.outputs.value }} ${{ steps.summary.outputs.value }}
            ${{ steps.description.outputs.value }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

