name: Versioning Workflow
on:
  pull_request:
    types:
      - closed

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Set Up
        run: |
          git config --global user.email "valeryk@bynet.co.il"
          git config --global user.name "ValeryKhirin"

      - name: Determine version increment
        id: versiontype
        run: |
          case "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" in
            patch*) 
              uses: anothrNick/github-tag-action@1.36.0 
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: PATCH
                INITIAL_VERSION: 0.0.0;;
            feature*)
              uses: anothrNick/github-tag-action@1.36.0 
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: MINOR
                INITIAL_VERSION: 0.0.0;;
            release*)
              uses: anothrNick/github-tag-action@1.36.0 
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: PATCH
                INITIAL_VERSION: 0.0.0;;
            *) echo "none" ;;
          esac

      # - name: Print
      #   run: echo "${{ steps.versiontype.outputs.value }}"

      # - name: Inrease Patch
      #   id: patch
      #   if: ${{ steps.versiontype.outputs.value == 'patch' }}
      #   uses: anothrNick/github-tag-action@1.36.0 
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: PATCH
      #     INITIAL_VERSION: 0.0.0

      # - name: Increase Minor
      #   id: minor
      #   if: ${{steps.versiontype.outputs.value == 'minor' }}
      #   uses: anothrNick/github-tag-action@1.36.0 
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: MINOR
      #     INITIAL_VERSION: 0.0.0

      # - name: Increase Major
      #   id: major
      #   if: ${{ steps.versiontype.outputs.value == 'major' }}
      #   uses: anothrNick/github-tag-action@1.36.0 
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: MQAJOR
      #     INITIAL_VERSION: 0.0.0

                # Extract last tag

          # Check if exists, if not ---> initialize 0.0.1

          # If yes, determine change type

          # Increase version accordingly

          # Push release with GitHub release API

          # Store artifact 