name: Versioning Workflow
on:
  pull_request:
    types: [closed]
jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check branch name and increment version
        run: |
          # Get the branch name from the event payload
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")

          # Set the initial version number
          CURRENT_VERSION="0.0.0"

          # Increment the version number based on the branch name
          if [[ $BRANCH_NAME == "patch"* ]]; then
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$3++; print}')
          elif [[ $BRANCH_NAME == "feature"* ]]; then
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$2++; print}')
          elif [[ $BRANCH_NAME == "release"* ]]; then
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$1++; print}')
          fi

          # # Set the new version number as an environment variable
          # echo "::set-env name=NEW_VERSION::$NEW_VERSION"
      
      - name: Update version number
        run: |
          # Replace this command with the one that fits your project setup
          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" ../../version.txt