name: Tag Version on Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine current tag
        id: current-tag
        run: |
          curl -s 'https://github.com/ValeryKhirin/github-image-push-action/tags/' | grep -Eo "tag/[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}" | awk -F '\/' '{print $2}' | sort -r | head -n1 >> current_tag.txt
          if [ -z "${VAR}" ]; then echo "0.0.0" >> current_tag.txt; fi

      - name: Determine branch name
        id: branch-name
        run: |
          tag=$(cat current_tag.txt)
          case "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" in
            patch*) echo "$tag" | awk -F '\.' '{print $1 "." $2 "." $3+1}' >> increment_tag.txt ;;
            feature*) echo "$tag" | awk -F '\.' '{print $1 "." $2+1 "." $3}' >> increment_tag.txt ;;
            release*) echo "$tag" | awk -F '\.' '{print $1+1 "." $2 "." $3}' >> increment_tag.txt ;;
            *) echo $tag >> increment_tag.txt ;;
          esac
          cat increment_tag.txt

      - name: Create tag
        id: create-tag
        run: |
          cat increment_tag.txt
          git config --local user.email "valeryk@bynet.co.il"
          git config --local user.name "ValeryKhirin"
          git tag $(cat increment_tag.txt)
          git push origin $(cat increment_tag.txt)
