name: Versioning Workflow
on:
  pull_request:
    types:
      - closed

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Set Up
        run: |
          git config --global user.email "valeryk@bynet.co.il"
          git config --global user.name "ValeryKhirin"

      - name: Determine version increment
        id: version_type
        run: |
          case "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" in
            patch*) echo "patch" ;;
            feature*) echo "minor" ;;
            release*) echo "major" ;;
            *) echo "none" ;;
          esac

      - name: Inrease Patch
        id: patch
        if: ${{ steps.version_type.outputs.value == 'patch' }}
        uses: anothrNick/github-tag-action@1.36.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: PATCH
          INITIAL_VERSION: 0.0.0

      - name: Increase Minor
        id: minor
        if: ${{steps.version_type.outputs.value == 'minor' }}
        uses: anothrNick/github-tag-action@1.36.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: MINOR
          INITIAL_VERSION: 0.0.0

      - name: Increase Major
        id: major
        if: ${{ steps.version_type.outputs.value == 'major' }}
        uses: anothrNick/github-tag-action@1.36.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: MQAJOR
          INITIAL_VERSION: 0.0.0