name: Versioning

on:
  pull_request:
    types: [closed]

jobs:
  scan:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3