name: Versioning Workflow
on:
  pull_request:
    types:
      - closed

jobs:
  update_version:
    runs-on: ubuntu-latest
    environment: VERSIONING
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Set Up
        run: |
          git config --global user.email "valeryk@bynet.co.il"
          git config --global user.name "ValeryKhirin"

      - name: Set Variables
        uses: marcdomain/set-variables@v1
        with:
            variables: | 
              VERSION: "1.0.0"

      - name: Determine version increment
        id: version_type
        run: |
          case "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" in
            patch*) echo "patch" ;;
            feature*) echo "minor" ;;
            release*) echo "major" ;;
            *) echo "none" ;;
          esac

      - name: Update VERSION file
        if: steps.version_type.outputs.value != 'none'
        run: |
          echo "${{ env.VERSION }}"
          IFS='.' read -ra version <<< "$(echo ${{ env.VERSION }})"
          case "${{ steps.version_type.outputs.value }}" in
            patch) version[2]=$((version[2]+1)) ;;
            minor) version[1]=$((version[1]+1)); version[2]=0 ;;
            major) version[0]=$((version[0]+1)); version[1]=0; version[2]=0 ;;
          esac
          VERSION="${version[0]}.${version[1]}.${version[2]}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Git tag
        if: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.VERSION_TOKEN }}
        run: |
          git tag ${{ env.VERSION }}
          git push --tags origin ${{ env.VERSION }}