name: Semantic Versioning

on:
  pull_request:
    types: [closed]

jobs:
  semantic-versioning:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Version
        if: github.event.pull_request.merged == true
        env:
          GITHUB_REF_SLUG: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ "$GITHUB_REF_SLUG" =~ ^patch/.*$ ]]; then
            version="1.0.1"
          elif [[ "$GITHUB_REF_SLUG" =~ ^feature/.*$ ]]; then
            version="1.1.0"
          elif [[ "$GITHUB_REF_SLUG" =~ ^release/.*$ ]]; then
            version="2.0.0"
          fi
        
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\": \"$version\", \"name\": \"Version $version\"}"
