name: Versioning Workflow
on:
  pull_request:
    types: [closed]

jobs:
  update_version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Version
        id: version
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/.* ]]; then
              echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
              branch=$(echo ${GITHUB_REF#refs/heads/})
              if [[ $branch =~ ^feature.* ]]; then
                  part=2
              elif [[ $branch =~ ^release.* ]]; then
                  part=1
              elif [[ $branch =~ ^patch.* ]]; then
                  part=3
              fi
              current_version=$(echo $VERSION | cut -d "." -f $part)
              new_version=$(($current_version + 1))
              new_version=$(echo $VERSION | awk -v new_version="$new_version" -v part="$part" 'BEGIN {FS=OFS="."} {$part=new_version; for (i=part+1;i<=NF;i++) $(i)=0; print}')
              echo "::set-output name=tag::v$new_version"
              echo "export VERSION=$new_version" >> $GITHUB_ENV
          fi
          
      - name: Create Git tag
        if: ${{ steps.version.outputs.tag }} != ${{ env.VERSION }}
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}