name: Versioning Workflow
on:
  pull_request:
    types: [closed]

env:
  VERSION: 0.0.0

jobs:
  update_version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "ValeryKhirin"
          git config user.email "valerykhirin@gmail.com"
      
      - name: Determine version number
        id: version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/patch"* ]]; then
            TAG_ARRAY=($(echo ${{ env.VERSION }} | tr '.' ' '))
            TAG="${TAG_ARRAY[0]}.${TAG_ARRAY[1]}.$((${TAG_ARRAY[2]}+1))"
          elif [[ "${{ github.ref }}" == "refs/heads/feature"* ]]; then
            TAG_ARRAY=($(echo ${{ env.VERSION }} | tr '.' ' '))
            TAG="${TAG_ARRAY[0]}.$((${TAG_ARRAY[1]}+1)).0"
          elif [[ "${{ github.ref }}" == "refs/heads/release"* ]]; then
            TAG_ARRAY=($(echo ${{ env.VERSION }} | tr '.' ' '))
            TAG="$(( ${TAG_ARRAY[0]}+1 )).0.0"
          else
            TAG=${{ env.VERSION }}
          fi
          echo "::set-output name=tag::$TAG"

      - name: Create Git tag
        if: steps.version.outputs.tag != ${{ env.VERSION }}
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}