name: Versioning Workflow
on:
  pull_request:
    types: [closed]

env:
  VERSION: 0.0.0

jobs:
  update_version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Version
        id: version
        run: |
          # Get current version from environment variable
          current_version=$VERSION

          # Get branch name
          branch_name=$(echo $GITHUB_REF | sed 's|.*/||')

          # Set version based on branch name
          if [[ "$branch_name" == patch* ]]; then
            new_version=$(echo $current_version | awk -F. '{$NF+=1; OFS="."; print $0}')
          elif [[ "$branch_name" == feature* ]]; then
            new_version=$(echo $current_version | awk -F. '{$(NF-1)+=1; $NF=0; OFS="."; print $0}')
          elif [[ "$branch_name" == release* ]]; then
            new_version=$(echo $current_version | awk -F. '{$1+=1; $2=$3=0; OFS="."; print $0}')
          else
            echo "No version change"
            exit 1
          fi

          # Set output variable
          echo "::set-output name=tag::$new_version"

      - name: Create Git tag
        if: ${{ steps.version.outputs.tag != env.VERSION }}
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}