name: Semantic Versioning

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  semantic-versioning:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install semver utility
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g semver

      - name: Add Version
        if: github.event.pull_request.merged == true
        env:
          GITHUB_REF_SLUG: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          if [[ "$GITHUB_REF_SLUG" =~ patch* ]]; then
            version=$(git tag --sort=v:refname | tail -n1)
            version=$(semver bump patch $version)
          elif [[ "$GITHUB_REF_SLUG" =~ feature* ]]; then
            version=$(git tag --sort=v:refname | tail -n1)
            version=$(semver bump minor $version)
          elif [[ "$GITHUB_REF_SLUG" =~ release* ]]; then
            version=$(git tag --sort=v:refname | tail -n1)
            version=$(semver bump major $version)
          else
            echo "Skipping branch with name $GITHUB_REF_SLUG"
            exit 0
          fi
        
          if [[ -n "$version" ]]; then
            git config --global user.email "valeryk@bynet.co.il"
            git config --global user.name "ValeryKhirin"
          
            git tag "$version"
            git push origin "$version"
          else
            echo "Skipping tag creation for branch $GITHUB_REF_SLUG"
            exit 0
          fi

